/// @file Config.cpp
/// @brief Config implementation using yaml-cpp.

#include "core/Config.hpp"
#include <fstream>
#include <sstream>

namespace inferdeck::core {

Config::Config() = default;
Config::~Config() = default;

FullConfig Config::Load(const std::filesystem::path& config_path) {
    FullConfig config;

    std::ifstream file(config_path);
    if (!file.is_open()) {
        return config;
    }

    std::stringstream buffer;
    buffer << file.rdbuf();
    std::string yaml_content = buffer.str();

    // Parse YAML (simple key-value extraction for V1)
    std::istringstream stream(yaml_content);
    std::string line;
    std::string current_section;

    while (std::getline(stream, line)) {
        // Skip comments and empty lines
        if (line.empty() || line[0] == '#') continue;

        // Remove leading whitespace
        size_t start = line.find_first_not_of(" \t");
        if (start == std::string::npos) continue;
        line = line.substr(start);

        // Track sections
        if (line.back() == ':') {
            current_section = line.substr(0, line.size() - 1);
            continue;
        }

        // Parse key: value
        size_t colon = line.find(':');
        if (colon == std::string::npos) continue;

        std::string key = line.substr(0, colon);
        std::string value = line.substr(colon + 1);

        // Trim whitespace
        size_t end = key.find_last_not_of(" \t");
        if (end != std::string::npos) key = key.substr(0, end + 1);

        start = value.find_first_not_of(" \t\"'");
        if (start != std::string::npos) {
            value = value.substr(start);
            end = value.find_last_not_of(" \t\"'");
            if (end != std::string::npos) value = value.substr(0, end + 1);
        }

        // Build dotted key
        std::string dotted_key = current_section.empty() ? key : current_section + "." + key;
        flat_config_[dotted_key] = value;
    }

    // Apply defaults
    return config;
}

FullConfig Config::LoadFromString(const std::string& yaml_content) {
    // Temporary file for parsing
    std::filesystem::path temp = std::filesystem::temp_directory_path() / "gateway_temp.yml";
    std::ofstream file(temp);
    file << yaml_content;
    file.close();

    FullConfig config = Load(temp);
    std::filesystem::remove(temp);
    return config;
}

void Config::Save(const std::filesystem::path& config_path, const FullConfig& config) {
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return;
    }

    file << "# InferDeck Gateway Configuration\n";
    file << "# Generated by InferDeck installer\n\n";

    file << "server:\n";
    file << "  host: \"" << config.server.host << "\"\n";
    file << "  port: " << config.server.port << "\n";
    file << "  tls:\n";
    file << "    enabled: " << (config.server.tls_enabled ? "true" : "false") << "\n";
    file << "    cert_file: \"" << config.server.cert_file << "\"\n";
    file << "    key_file: \"" << config.server.key_file << "\"\n\n";

    file << "model:\n";
    file << "  path: \"" << config.model.path << "\"\n";
    file << "  precision: \"" << config.model.precision << "\"\n";
    file << "  n_gpu_layers: " << config.model.n_gpu_layers << "\n";
    file << "  context_size: " << config.model.context_size << "\n";
    file << "  batch_size: " << config.model.batch_size << "\n\n";

    file << "gpu:\n";
    file << "  device_id: " << config.gpu.device_id << "\n\n";

    file << "queue:\n";
    file << "  worker_threads: " << config.queue.worker_threads << "\n";
    file << "  max_queue_size: " << config.queue.max_queue_size << "\n\n";

    file << "logging:\n";
    file << "  level: \"" << config.logging.level << "\"\n";
    file << "  file: \"" << config.logging.file << "\"\n\n";

    file << "metrics:\n";
    file << "  enabled: " << (config.metrics_enabled ? "true" : "false") << "\n";
    file << "  endpoint: \"" << config.metrics_endpoint << "\"\n";

    file.close();
}

std::string Config::Get(const std::string& key) {
    auto it = Config::Get().flat_config_.find(key);
    return it != Config::Get().flat_config_.end() ? it->second : "";
}

int Config::GetInt(const std::string& key, int default_value) {
    auto it = Config::Get().flat_config_.find(key);
    if (it == Config::Get().flat_config_.end()) {
        return default_value;
    }
    try {
        return std::stoi(it->second);
    } catch (...) {
        return default_value;
    }
}

bool Config::GetBool(const std::string& key, bool default_value) {
    auto it = Config::Get().flat_config_.find(key);
    if (it == Config::Get().flat_config_.end()) {
        return default_value;
    }
    return it->second == "true" || it->second == "1";
}

} // namespace inferdeck::core
