set(VCPKG_INSTALLED_DIR "${CMAKE_CURRENT_LIST_DIR}/vcpkg_installed" CACHE PATH "" FORCE)
set(VCPKG_TARGET_TRIPLET "x64-windows" CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/cmake/vcpkg-msvc.cmake" CACHE FILEPATH "" FORCE)
